osoby/urls.py
from django.urls import path

from . import views

app_name = 'osoby'
urlpatterns = [
    path('', views.index, name='index'),
    path('lista/', views.lista, name='lista'),
    path('loguj/', views.loguj_osobe, name='loguj-osobe'),
    path('wyloguj/', views.wyloguj_osobe, name='wyloguj-osobe'),
    path('rejestruj/', views.rejestruj_osobe, name='rejestruj-osobe'),
    path('edytuj/', views.edytuj_osobe, name='edytuj-osobe'),
]

projekt/projekt/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

projekt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('wiadomosci/', include('wiadomosci.urls')),
    path('osoby/', include('osoby.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/wiadomosci/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiadomosci/urls.py
from django.urls import path

from . import views

app_name = 'wiadomosci'
urlpatterns = [
   path('', views.lista_wiadomosci, name='lista'),
   path('dodaj/', views.dodaj_wiadomosc, name='dodaj'),
]

wiadomosci/models.py
from django.db import models

from django.contrib.auth.models import User
from django.utils import timezone


class Wiadomosc(models.Model):
    tresc = models.TextField("treść wiadomości")
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    data_d = models.DateTimeField("dodana", default=timezone.now)

    class Meta:
        verbose_name = 'wiadomość'
        verbose_name_plural = 'wiadomości'
        ordering = ['-data_d',]

    def __str__(self):
        return self.tresc[0:50]+' {0:%Y-%m-%d %H:%M:%S}'.format(self.data_d)

wiadomosci/forms.py
from django import forms
from wiadomosci.models import Wiadomosc


class WiadomoscForm(forms.ModelForm):
    class Meta:
        model = Wiadomosc
        fields = ('tresc', 'data_d')
        widgets = {
            'tresc': forms.Textarea(attrs={'cols': 100, 'rows': 2, 'class': 'form-control'}
),
            'data_d': forms.DateTimeInput(),
        }

wiadomosci/views.py
from django.shortcuts import render
from wiadomosci.models import Wiadomosc
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from wiadomosci.forms import WiadomoscForm
from django.contrib.auth.decorators import login_required

def lista_wiadomosci(request):
    wiadomosci = Wiadomosc.objects.all()
    kontekst = {'wiadomosci': wiadomosci}
    return render(request, 'wiadomosci/lista_wiadomosci2.html', kontekst)

@login_required()
def dodaj_wiadomosc(request):
    if request.method == 'POST':
        form = WiadomoscForm(request.POST)
        if form.is_valid():
            w = Wiadomosc(tresc=form.cleaned_data['tresc'], autor=request.user, data_d=form.cleaned_data['data_d'])
            w.save()
            messages.success(request, "Dodano nową wiadomość!")
            return redirect(reverse('wiadomosci:lista'))
    else:
        form = WiadomoscForm()
    return render(request, 'wiadomosci/dodaj_wiadomosc3.html', {'form': form})

wiadomosci/templates/wiadomosci/dodaj_wiadomosc1.html
{% extends 'szablon.html' %}
{% block tytul %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block h1 %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block tresc %}
    <div class="w-100 bg-faded rounded p-4">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary">Wyślij</button>
        </form>
    </div>
{% endblock %}

wiadomosci/templates/wiadomosci/dodaj_wiadomosc2.html
{% extends 'szablon.html' %}
{% block tytul %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block h1 %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block tresc %}
    <div class="w-100 bg-faded rounded p-4">
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary">Wyślij</button>
        </form>
    {% else %}
        <div class="well">Nie jesteś zalogowany!</div>
    {% endif %}
    </div>
{% endblock %}

wiadomosci/templates/wiadomosci/dodaj_wiadomosc3.html
{% extends 'szablon.html' %}
{% block tytul %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block h1 %}Absolwent – Dodawanie wiadomości{% endblock %}
{% block tresc %}
    <div class="w-100 bg-faded rounded p-4">
    {% if user.is_authenticated %}
        {% if perms.wiadomosci.add_wiadomosc %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Wyślij</button>
            </form>
        {% else %}
            <div class="well">Nie możesz dodawać wiadomości!</div>
        {% endif %}
    {% else %}
        <div class="well">Nie jesteś zalogowany!</div>
    {% endif %}
    </div>
{% endblock %}

wiadomosci/templates/wiadomosci/lista_wiadomosci1.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Lista wiadomości</title>
</head>
<body>
    <h1>Aktualności</h1>
    <ol>
    {% for w in wiadomosci %}
        <li>{{ w.tresc }}<br><span>Dodano: {{ w.data_d }}</span></li>
    {% endfor %}
    </ol>
</body>
</html>

wiadomosci/templates/wiadomosci/lista_wiadomosci2.html
{% extends 'szablon.html' %}

{% block tresc %}
    <div class="w-100 bg-primary rounded p-4">
        <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Przeczytaj</span>
            <span class="section-heading-lower">Aktualności</span>
        </h2>

        <ul>
        {% for w in wiadomosci %}
        <li class="mb-5">
            <span class="lead">{{ w.tresc }}</span><br>
            <span class="float-right">Dodano: {{ w.data_d }}</span>
        </li>
        {% endfor %}
        </ul>

        {% if user.is_authenticated %}
            <a href="{% url 'wiadomosci:dodaj' %}" class="btn btn-secondary">Dodaj wiadomość</a>
        {% endif %}

    </div>
{% endblock %}